const patientChartList = [
  {
    num_of_days_since_last_intervention: { value: 25, alarm_is_active: 0 },
    num_of_calls: { value: 29, alarm_is_active: 0 },
    num_of_visits: { value: 28, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Dorothy A. Davenport",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 9, alarm_is_active: 0 },
    num_of_calls: { value: 23, alarm_is_active: 0 },
    num_of_visits: { value: 25, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Blake N. Hampton",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 29, alarm_is_active: 0 },
    num_of_calls: { value: 7, alarm_is_active: 0 },
    num_of_visits: { value: 19, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Sean G. Salazar",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 25, alarm_is_active: 0 },
    num_of_calls: { value: 5, alarm_is_active: 0 },
    num_of_visits: { value: 11, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Daniel C. Velez",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 6, alarm_is_active: 0 },
    num_of_calls: { value: 5, alarm_is_active: 0 },
    num_of_visits: { value: 28, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Thomas W. Hinton",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 21, alarm_is_active: 0 },
    num_of_calls: { value: 16, alarm_is_active: 0 },
    num_of_visits: { value: 15, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Pierre D. Wren",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 5, alarm_is_active: 0 },
    num_of_calls: { value: 12, alarm_is_active: 0 },
    num_of_visits: { value: 10, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Minnie B. Robinson",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 7, alarm_is_active: 0 },
    num_of_calls: { value: 7, alarm_is_active: 0 },
    num_of_visits: { value: 20, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Arlene C. Pickel",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 17, alarm_is_active: 0 },
    num_of_calls: { value: 12, alarm_is_active: 0 },
    num_of_visits: { value: 18, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Rosemary J. Posey",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 29, alarm_is_active: 0 },
    num_of_calls: { value: 13, alarm_is_active: 0 },
    num_of_visits: { value: 27, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Kirk J. Tincher",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 19, alarm_is_active: 0 },
    num_of_calls: { value: 6, alarm_is_active: 0 },
    num_of_visits: { value: 3, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Beverly N. Couts",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 25, alarm_is_active: 0 },
    num_of_calls: { value: 11, alarm_is_active: 0 },
    num_of_visits: { value: 19, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Harlan N. Christiansen",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 30, alarm_is_active: 0 },
    num_of_calls: { value: 20, alarm_is_active: 0 },
    num_of_visits: { value: 12, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Adam J. Gammon",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 14, alarm_is_active: 0 },
    num_of_calls: { value: 4, alarm_is_active: 0 },
    num_of_visits: { value: 19, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Manuela N. Teyler",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 18, alarm_is_active: 0 },
    num_of_calls: { value: 14, alarm_is_active: 0 },
    num_of_visits: { value: 27, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Patti C. Calkins",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 28, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 25, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Enid N. Wright",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 30, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 15, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Heather T. Jones",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 13, alarm_is_active: 0 },
    num_of_calls: { value: 3, alarm_is_active: 0 },
    num_of_visits: { value: 4, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Manuel J. Bulle",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 13, alarm_is_active: 0 },
    num_of_calls: { value: 12, alarm_is_active: 0 },
    num_of_visits: { value: 20, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Jeremiah E. Gordon",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 23, alarm_is_active: 0 },
    num_of_calls: { value: 4, alarm_is_active: 0 },
    num_of_visits: { value: 2, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "David K. Austin",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 8, alarm_is_active: 0 },
    num_of_calls: { value: 15, alarm_is_active: 0 },
    num_of_visits: { value: 17, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Laura A. Henderson",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 9, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 21, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Paul I. Caskey",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 28, alarm_is_active: 0 },
    num_of_calls: { value: 13, alarm_is_active: 0 },
    num_of_visits: { value: 1, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "James G. Steinert",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 25, alarm_is_active: 0 },
    num_of_calls: { value: 21, alarm_is_active: 0 },
    num_of_visits: { value: 21, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Alan R. Anderson",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 6, alarm_is_active: 0 },
    num_of_calls: { value: 28, alarm_is_active: 0 },
    num_of_visits: { value: 4, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Paul N. Roder",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 30, alarm_is_active: 0 },
    num_of_calls: { value: 17, alarm_is_active: 0 },
    num_of_visits: { value: 12, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Betty N. Little",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 26, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Nancy N. Johnston",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 15, alarm_is_active: 0 },
    num_of_calls: { value: 2, alarm_is_active: 0 },
    num_of_visits: { value: 2, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Russell R. Paider",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 15, alarm_is_active: 0 },
    num_of_calls: { value: 3, alarm_is_active: 0 },
    num_of_visits: { value: 7, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Steven N. Jones",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 19, alarm_is_active: 0 },
    num_of_calls: { value: 16, alarm_is_active: 0 },
    num_of_visits: { value: 2, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Kristine J. Farr",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 15, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 14, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Chelsea S. Grijalva",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 24, alarm_is_active: 0 },
    num_of_calls: { value: 18, alarm_is_active: 0 },
    num_of_visits: { value: 16, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Jerry L. Hutching",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 6, alarm_is_active: 0 },
    num_of_calls: { value: 28, alarm_is_active: 0 },
    num_of_visits: { value: 25, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Michael D. Greene",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 24, alarm_is_active: 0 },
    num_of_calls: { value: 12, alarm_is_active: 0 },
    num_of_visits: { value: 28, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Wendy B. Richmond",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 26, alarm_is_active: 0 },
    num_of_calls: { value: 8, alarm_is_active: 0 },
    num_of_visits: { value: 29, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Jennifer S. Sykes",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 18, alarm_is_active: 0 },
    num_of_calls: { value: 5, alarm_is_active: 0 },
    num_of_visits: { value: 30, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Tricia M. Rollag",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 10, alarm_is_active: 0 },
    num_of_calls: { value: 14, alarm_is_active: 0 },
    num_of_visits: { value: 12, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Mary R. Bailey",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 24, alarm_is_active: 0 },
    num_of_calls: { value: 5, alarm_is_active: 0 },
    num_of_visits: { value: 22, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Rosemary J. Wilkins",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 18, alarm_is_active: 0 },
    num_of_calls: { value: 26, alarm_is_active: 0 },
    num_of_visits: { value: 1, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Susan J. Barker",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 10, alarm_is_active: 0 },
    num_of_calls: { value: 9, alarm_is_active: 0 },
    num_of_visits: { value: 26, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Timothy K. Friday",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 21, alarm_is_active: 0 },
    num_of_calls: { value: 24, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Treena J. Beu",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 22, alarm_is_active: 0 },
    num_of_calls: { value: 3, alarm_is_active: 0 },
    num_of_visits: { value: 4, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Pamela A. Pickett",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 5, alarm_is_active: 0 },
    num_of_calls: { value: 20, alarm_is_active: 0 },
    num_of_visits: { value: 7, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Ethel N. Barger",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 24, alarm_is_active: 0 },
    num_of_calls: { value: 29, alarm_is_active: 0 },
    num_of_visits: { value: 24, alarm_is_active: 0 },
    riesgo_clinico: { value: 3, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Stacy N. Clay",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 20, alarm_is_active: 0 },
    num_of_calls: { value: 12, alarm_is_active: 0 },
    num_of_visits: { value: 17, alarm_is_active: 0 },
    riesgo_clinico: { value: 1, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Thurman R. Bookout",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 20, alarm_is_active: 0 },
    num_of_calls: { value: 16, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    user_name: "Joseph T. Stahnke",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 14, alarm_is_active: 0 },
    num_of_calls: { value: 27, alarm_is_active: 0 },
    num_of_visits: { value: 11, alarm_is_active: 0 },
    riesgo_clinico: { value: 2, alarm_is_active: 0 },
    riesgo_por_entorno: { value: 2, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    user_name: "Sara P. Way",
    general_alarm_is_active: 0,
  },
  {
    num_of_days_since_last_intervention: { value: 10, alarm_is_active: 0 },
    num_of_calls: { value: 16, alarm_is_active: 0 },
    num_of_visits: { value: 4, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Kyle C. Samuels",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 10, alarm_is_active: 0 },
    num_of_calls: { value: 17, alarm_is_active: 0 },
    num_of_visits: { value: 25, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 3, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "Peter D. Rohde",
    general_alarm_is_active: 1,
  },
  {
    num_of_days_since_last_intervention: { value: 24, alarm_is_active: 0 },
    num_of_calls: { value: 15, alarm_is_active: 0 },
    num_of_visits: { value: 23, alarm_is_active: 0 },
    riesgo_clinico: { value: 4, alarm_is_active: 1 },
    riesgo_por_entorno: { value: 4, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    user_name: "David N. Dam",
    general_alarm_is_active: 1,
  },
];

export default patientChartList;
