const pdsChartList = [
  {
    community_worker_name: "Emery C. Kelly",
    general_alarm_is_active: 1,
    num_of_calls: { value: 3, alarm_is_active: 1 },
    num_of_visits: { value: 2, alarm_is_active: 1 },
    duration_of_call_in_mins: { value: 24, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 32, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 70, alarm_is_active: 1 },
    response_time_in_mins: { value: 371, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
  },
  {
    community_worker_name: "Thomas N. Gatlin",
    general_alarm_is_active: 1,
    num_of_calls: { value: 17, alarm_is_active: 0 },
    num_of_visits: { value: 3, alarm_is_active: 1 },
    duration_of_call_in_mins: { value: 12, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 80, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 51, alarm_is_active: 1 },
    response_time_in_mins: { value: 412, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 1, alarm_is_active: 1 },
  },
  {
    community_worker_name: "Ned H. Amerson",
    general_alarm_is_active: 0,
    num_of_calls: { value: 23, alarm_is_active: 0 },
    num_of_visits: { value: 4, alarm_is_active: 1 },
    duration_of_call_in_mins: { value: 37, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 32, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 74, alarm_is_active: 1 },
    response_time_in_mins: { value: 113, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 5, alarm_is_active: 1 },
  },
  {
    community_worker_name: "Doretha E. Rawlings",
    general_alarm_is_active: 1,
    num_of_calls: { value: 25, alarm_is_active: 0 },
    num_of_visits: { value: 9, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 25, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 65, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 21, alarm_is_active: 0 },
    response_time_in_mins: { value: 41, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
  },
  {
    community_worker_name: "Gaye B. Robinson",
    general_alarm_is_active: 0,
    num_of_calls: { value: 24, alarm_is_active: 0 },
    num_of_visits: { value: 6, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 27, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 64, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 88, alarm_is_active: 1 },
    response_time_in_mins: { value: 303, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 1, alarm_is_active: 1 },
  },
  {
    community_worker_name: "Danny S. Tucker",
    general_alarm_is_active: 1,
    num_of_calls: { value: 18, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 51, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 118, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 42, alarm_is_active: 1 },
    response_time_in_mins: { value: 365, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 6, alarm_is_active: 1 },
  },
  {
    community_worker_name: "Merrill N. Palmer",
    general_alarm_is_active: 1,
    num_of_calls: { value: 7, alarm_is_active: 1 },
    num_of_visits: { value: 4, alarm_is_active: 1 },
    duration_of_call_in_mins: { value: 8, alarm_is_active: 1 },
    duration_of_visit_in_mins: { value: 25, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 52, alarm_is_active: 1 },
    response_time_in_mins: { value: 244, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 6, alarm_is_active: 1 },
  },
  {
    community_worker_name: "Shirley N. Mccord",
    general_alarm_is_active: 0,
    num_of_calls: { value: 15, alarm_is_active: 0 },
    num_of_visits: { value: 2, alarm_is_active: 1 },
    duration_of_call_in_mins: { value: 15, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 48, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 9, alarm_is_active: 0 },
    response_time_in_mins: { value: 82, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 7, alarm_is_active: 0 },
  },
  {
    community_worker_name: "Stephen H. Donaldson",
    general_alarm_is_active: 1,
    num_of_calls: { value: 25, alarm_is_active: 0 },
    num_of_visits: { value: 7, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 48, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 98, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 28, alarm_is_active: 0 },
    response_time_in_mins: { value: 249, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 7, alarm_is_active: 0 },
  },
  {
    community_worker_name: "Ann N. Navarro",
    general_alarm_is_active: 0,
    num_of_calls: { value: 20, alarm_is_active: 0 },
    num_of_visits: { value: 9, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 5, alarm_is_active: 1 },
    duration_of_visit_in_mins: { value: 118, alarm_is_active: 1 },
    duration_of_travel_in_mins: { value: 38, alarm_is_active: 1 },
    response_time_in_mins: { value: 370, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
  },
];

export default pdsChartList;
