const pdsChartList = [
  {
    num_of_calls: { value: 23, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 51, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 40, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 8, alarm_is_active: 0 },
    response_time_in_mins: { value: 316, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    community_worker_name: "Emery C. Kelly",
    general_alarm_is_active: 1,
  },
  {
    num_of_calls: { value: 24, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 19, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 60, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 24, alarm_is_active: 0 },
    response_time_in_mins: { value: 106, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    community_worker_name: "Thomas N. Gatlin",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 16, alarm_is_active: 0 },
    num_of_visits: { value: 9, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 13, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 34, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 19, alarm_is_active: 0 },
    response_time_in_mins: { value: 94, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    community_worker_name: "Ned H. Amerson",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 30, alarm_is_active: 0 },
    num_of_visits: { value: 9, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 15, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 29, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 13, alarm_is_active: 0 },
    response_time_in_mins: { value: 328, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    community_worker_name: "Doretha E. Rawlings",
    general_alarm_is_active: 1,
  },
  {
    num_of_calls: { value: 23, alarm_is_active: 0 },
    num_of_visits: { value: 6, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 45, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 48, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 13, alarm_is_active: 0 },
    response_time_in_mins: { value: 41, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 8, alarm_is_active: 0 },
    community_worker_name: "Gaye B. Robinson",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 20, alarm_is_active: 0 },
    num_of_visits: { value: 5, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 55, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 27, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 6, alarm_is_active: 0 },
    response_time_in_mins: { value: 1, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    community_worker_name: "Danny S. Tucker",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 18, alarm_is_active: 0 },
    num_of_visits: { value: 10, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 23, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 60, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 19, alarm_is_active: 0 },
    response_time_in_mins: { value: 237, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    community_worker_name: "Merrill N. Palmer",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 26, alarm_is_active: 0 },
    num_of_visits: { value: 6, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 39, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 19, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 25, alarm_is_active: 0 },
    response_time_in_mins: { value: 96, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 7, alarm_is_active: 0 },
    community_worker_name: "Shirley N. Mccord",
    general_alarm_is_active: 0,
  },
  {
    num_of_calls: { value: 17, alarm_is_active: 0 },
    num_of_visits: { value: 6, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 41, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 41, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 15, alarm_is_active: 0 },
    response_time_in_mins: { value: 395, alarm_is_active: 1 },
    patient_satisfaction_level: { value: 9, alarm_is_active: 0 },
    community_worker_name: "Stephen H. Donaldson",
    general_alarm_is_active: 1,
  },
  {
    num_of_calls: { value: 20, alarm_is_active: 0 },
    num_of_visits: { value: 6, alarm_is_active: 0 },
    duration_of_call_in_mins: { value: 34, alarm_is_active: 0 },
    duration_of_visit_in_mins: { value: 34, alarm_is_active: 0 },
    duration_of_travel_in_mins: { value: 28, alarm_is_active: 0 },
    response_time_in_mins: { value: 53, alarm_is_active: 0 },
    patient_satisfaction_level: { value: 10, alarm_is_active: 0 },
    community_worker_name: "Ann N. Navarro",
    general_alarm_is_active: 0,
  },
];

export default pdsChartList;
