const pendingEvents = [
  {
    date: "2021-10-11",
    pds_first_name: "Tammie",
    pds_middle_name: "Craig",
    pds_last_name: "Jenkins",
    patient_first_name: "Ruby",
    patient_middle_name: "",
    patient_last_name: "Stout",
    patient_residence_address: "15 Colonial Lane Manati",
    patient_residence_city: "",
    patient_residence_state: "Puerto Rico",
    patient_residence_country_name: "United States",
    patient_phone_country_code_num: "1",
    patient_phone_num: "780059478",
  },
  {
    date: "2021-11-14",
    pds_first_name: "Tammie",
    pds_middle_name: "Craig",
    pds_last_name: "Jenkins",
    patient_first_name: "Lawrence",
    patient_middle_name: "Linda",
    patient_last_name: "Burgess",
    patient_residence_address: "89 N.Howard Avenue Rosario",
    patient_residence_city: "",
    patient_residence_state: "Puerto Rico",
    patient_residence_country_name: "United States",
    patient_phone_country_code_num: "1",
    patient_phone_num: "505694255",
  },
  {
    date: "2021-11-13",
    pds_first_name: "Tammie",
    pds_middle_name: "Craig",
    pds_last_name: "Jenkins",
    patient_first_name: "Georgia",
    patient_middle_name: "Mike",
    patient_last_name: "Miller",
    patient_residence_address: "97 Parkside Dr.Guaynabo",
    patient_residence_city: "",
    patient_residence_state: "Puerto Rico",
    patient_residence_country_name: "United States",
    patient_phone_country_code_num: "1",
    patient_phone_num: "797373883",
  },
  {
    date: "2021-11-18",
    pds_first_name: "Tammie",
    pds_middle_name: "Craig",
    pds_last_name: "Jenkins",
    patient_first_name: "Cory",
    patient_middle_name: "",
    patient_last_name: "Pefferkorn",
    patient_residence_address: "864 South Wentworth St.Quebradillas",
    patient_residence_city: "",
    patient_residence_state: "Puerto Rico",
    patient_residence_country_name: "United States",
    patient_phone_country_code_num: "1",
    patient_phone_num: "486228899",
  },
  {
    date: "2021-11-10",
    pds_first_name: "Tammie",
    pds_middle_name: "Craig",
    pds_last_name: "Jenkins",
    patient_first_name: "Joan",
    patient_middle_name: "",
    patient_last_name: "Haifley",
    patient_residence_address: "9958 Senna Drive Punta Santiago",
    patient_residence_city: "",
    patient_residence_state: "Puerto Rico",
    patient_residence_country_name: "United States",
    patient_phone_country_code_num: "1",
    patient_phone_num: "775082986",
  },
];

export default pendingEvents;
